name: recipe_app
description: A new Flutter project.

publish_to: 'none' 

environment:
  sdk: ">=3.5.4 <=4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/place1.png
    - assets/images/place2.png
    - assets/images/place3.png
    - assets/images/place4.png
    - assets/images/place5.png
    - assets/images/place6.png
    - assets/images/place7.png
    - assets/images/place8.png
    - assets/images/place9.png
    - assets/images/place10.png
